---
- name: Checkout repo with manifest files
  ansible.builtin.git:
    repo: "{{ k8s_config_repo }}"
    dest: "{{ k8s_config_repo_path }}"
    version: "{{ k8s_config_version }}"

- name: Create app namespace in k8s cluster
  ansible.builtin.shell:
    chdir: "{{ k8s_config_repo_path }}"
    cmd: kubectl apply -f {{ k8s_namespaces_config }}

- name: Deploy app to k8S cluster
  ansible.builtin.shell:
    chdir: "{{ k8s_config_repo_path }}/{{ k8s_helmfile_dir }}"
    cmd: helmfile sync

- name: Cleanup
  ansible.builtin.file:
    path:  "{{ k8s_config_repo_path }}"
    state: absent
    