---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Reboot the system
    ansible.builtin.reboot:
  when: reboot_after_update
