---
docker_image_archives_dir_dest: /docker_image_archives/arm/
docker_image_archives_dir_src: /docker_image_archives/arm/

videos_dir_dest: /videos/
videos_dir_src: /videos/

docker_compose_dir_dest: /docker_compose/encoding-app/
docker_compose_dir_src: /docker_compose/encoding-app/

encoder_img_archive_name: encoder-x265-img.tar
frontend_img_archive_name: frontend-encoding-img.tar