---
- name: Pull Nexus Docker image
  community.docker.docker_image:
    name: sonatype/nexus3:{{ nexus_version }}
    source: pull
    pull:
      platform: "{{ nexus_target_platform }}"
    state: present

- name: Create Docker volume for Nexus data
  community.docker.docker_volume:
    name: nexus-data
    state: present

- name: Run Nexus Docker container
  community.docker.docker_container:
    name: nexus
    image: sonatype/nexus3:{{ nexus_version }}
    ports:
      - "{{ nexus_port }}:8081"
    volumes:
      - nexus-data:/nexus-data
    state: started
