frontend_port:        8080
encoding_endpoint:    encode
encoder_img_version:  latest
frontend_img_version: latest
encoder_img_name:     encoder-x265-img
frontend_img_name:    frontend-encoding-img
docker_registry:      https://hub.docker.com/repository/docker/anea11/encoding/
