---
- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Add Ansible PPA repository
  ansible.builtin.apt_repository:
    repo: 'ppa:ansible/ansible'
    update_cache: yes

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present
