- name: Deploy monitoring stack
  hosts: localhost

  roles:
    - role: deploy_monitoring_stack
      vars:
        k8s_config_repo: https://github.com/anea-11/kubernetes-manifests
        k8s_config_version: main
        k8s_namespaces_config: global/namespaces/ns_monitoring.yaml
        monitoring_deploy_script: monitoring/helm/deploy-prometheus-and-grafana.sh
        grafana_lb_config_file: monitoring/grafana-ext.yaml
