---
- name: Initial Jenkins server configuration
  hosts: jenkins_servers
  become: yes

  roles:
    - role: update_all_packages
      vars:
        reboot_after_update: true

    - role: install_jenkins

    - role: install_docker
