---
- name: Initial Encoding server configuration
  hosts: encoding_servers
  become: yes

  roles:

    - role: update_all_packages
      vars:
        reboot_after_update: true

    - role: install_docker
      vars:
        user_to_add_to_docker_group: ubuntu

    - role: deploy_encoding_app
      vars:
        frontend_port: 8080
        encoding_endpoint: encode
        encoder_img_version: 0
        frontend_img_version: 0
