---
- name: Initial Nexus server configuration
  hosts: nexus_servers
  become: yes

  tasks:

    - import_role:
        name: update_all_packages
        vars:
          reboot_after_update: true

    - import_role: 
        name: install_docker

    - import_role: 
        name: install_nexus_dockerized

