---
- name: Initial Jenkins server configuration
  hosts: jenkins_servers
  become: yes

  tasks:

    - import_role:
        name: update_all_packages
        vars:
          reboot_after_update: true

    - import_role:
        name: install_jenkins

    - import_role: 
        name: install_docker
