---
- name: Initial Nexus server configuration
  hosts: nexus_servers
  become: yes

  roles:

    - role: update_all_packages
      vars:
        reboot_after_update: true

    - role: install_docker

    - role: install_nexus_dockerized

