---
- name: Initial Encoding server configuration
  hosts: encoding_servers
  become: yes

  roles:

    - role: update_all_packages
      vars:
        reboot_after_update: true

    - role: install_docker

    - role: deploy_encoding_app
