---
- name: Initial Encoding server configuration
  hosts: encoding_servers
  become: yes

  tasks:
    - import_role:
        name: update_all_packages

    - name: Reboot the system
      ansible.builtin.reboot:

    - import_role: 
        name: install_docker

    - import_role:
        name: deploy_encoding_app

