---
- name: Initial Jenkins server configuration
  hosts: jenkins_servers
  become: yes

  tasks:

    - import_role:
        name: update_all_packages

    - name: Reboot the system
      ansible.builtin.reboot:

    - import_role:
        name: install_jenkins

    - import_role: 
        name: install_docker
