---
- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_pass }}"

- name: Pull encoder image
  community.docker.docker_image:
    name: "{{ docker_registry }}:{{ encoder_img_name }}-{{ encoder_img_version }}"
    source: pull

- name: Pull frontend image
  community.docker.docker_image:
    name: "{{ docker_registry }}:{{ frontend_img_name }}-{{ frontend_img_version }}"
    source: pull

- name: Log out of DockerHub
  community.docker.docker_login:
    state: absent

- name: Start encoding app containers
  community.docker.docker_compose:
    project_name: encoding-app
    definition:
      version: '3'
      services:
        encoding-service:
          image: "{{ encoder_img_name }}:{{ encoder_img_version }}"
          environment:
            - X265_ENC_HOSTNAME=0.0.0.0
            - X265_ENC_PORT=9000
          volumes:
            - "/videos:/videos"
        frontend-service:
          image: "{{ frontend_img_name }}:{{ frontend_img_version }}"
          environment:
            - WEBSERVER_HOSTNAME={{ ansible_host }}
            - WEBSERVER_PORT={{ frontend_port }}
            - ENCODING_ENDPOINT={{ encoding_endpoint }}
          ports:
            - "{{ frontend_port }}:80"
          depends_on:
            - encoding-service
    state: present
