---
- name: Copy Docker image archives to target
  ansible.builtin.copy:
    dest: "{{ docker_image_archives_dir_dest }}"
    src: "{{ docker_image_archives_dir_src }}"

- name: Copy sample videos to target
  ansible.builtin.copy:
    dest: "{{ videos_dir_dest }}"
    src: "{{ videos_dir_src }}"

- name: Load encoding service image
  community.docker.docker_image_load:
    path: "{{ docker_image_archives_dir_dest + encoder_img_name }}.tar"

- name: Load frontend service image
  community.docker.docker_image_load:
    path: "{{ docker_image_archives_dir_dest + frontend_img_name }}.tar"

- name: Delete docker image archives
  ansible.builtin.file:
    path: docker_image_archives_dir_dest
    state: absent

- name: Start encoding app containers
  community.docker.docker_compose:
    project_name: encoding-app
    definition:
      version: '3'
      services:
        encoding-service:
          image: "{{ encoder_img_name }}:{{ encoder_img_version }}"
          environment:
            - X265_ENC_HOSTNAME=0.0.0.0
            - X265_ENC_PORT=9000
          volumes:
            - "{{ videos_dir_dest }}:/videos"
        frontend-service:
          image: "{{ frontend_img_name }}:{{ frontend_img_version }}"
          environment:
            - WEBSERVER_HOSTNAME="{{ ansible_host }}"
            - WEBSERVER_PORT="{{ frontend_port }}"
            - ENCODING_ENDPOINT="{{ encoding_endpoint }}"
          ports:
            - "{{ frontend_port }}:80"
          depends_on:
            - encoding-service
    state: present
