---
- name: Copy Docker image archives to target
  ansible.builtin.copy:
    dest: "{{ docker_image_archives_dir_dest }}"
    src: "{{ docker_image_archives_dir_src }}"

- name: Copy sample videos to target
  ansible.builtin.copy:
    dest: "{{ videos_dir_dest }}"
    src: "{{ videos_dir_src }}"

- name: Copy docker-compose to target
  ansible.builtin.copy:
    dest: "{{ docker_compose_dir_dest }}"
    src: "{{ docker_compose_dir_src }}"

- name: Load encoding service image
  community.docker.docker_image_load:
    path: "{{ docker_image_archives_dir_dest + encoder_img_archive_name }}"

- name: Load frontend service image
  community.docker.docker_image_load:
    path: "{{ docker_image_archives_dir_dest + frontend_img_archive_name }}"

- name: Delete docker image archives
  ansible.builtin.file:
    path: docker_image_archives_dir_dest
    state: absent

- name: Set hostname env var for frontend service
  replace:
    path: "{{ docker_compose_dir_dest }}docker-compose.yaml"
    regexp: 'localhost'
    replace: "{{ ansible_host }}"

- name: Start encoding app containers
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir_dest }}"
    state: present
